document.write("<p>Otros datos del navegador: -Versión: ");
document.write(infoNavegador.version);
document.write(", -Plataforma: ");
document.write(infoNavegador.plataforma);
document.write(", -Vendedor: ");
document.write(infoNavegador.vendedor);
document.write(", -Agente: ");
document.write(infoNavegador.agente);
document.write(", -Java activo: ");
document.write(infoNavegador.javaActivo);
document.write("</p>");