document.write("<section>");
document.write("<h2>Datos completos de la asignatura: </h2>");

document.write("<p>Nombre de la Asignatura: ");
document.write(asignatura.nombre);
document.write("</p>");
document.write("<p>Titulación: ");
document.write(asignatura.titulacion);
document.write("</p>");
document.write("<p>Centro: ");
document.write(asignatura.centro);
document.write("</p>");
document.write("<p>Universidad: ");
document.write(asignatura.universidad);
document.write("</p>");
document.write("<p>Curso actual: ");
document.write(asignatura.curso);
document.write("</p>");
document.write("<p>Alumno: ");
document.write(asignatura.alumno);
document.write("</p>");
document.write("<p>e-mail: ");
document.write(asignatura.email);
document.write("</p>");
document.write("</section>");